import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";



export const metadata = {
  title: "Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ "antialiased w-screen h-screen flex justify-center items-center relative bg-[#F4F4F4]"}
      >
        {children}
      </body>
    </html>
  );
}
