import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div>
        <div className="flex h-screen justify-center content- center items-center relative">
      <div className="flex justify-center items-center h-screen w-screen">
       
     
        <div className="absolute  top-1/2 left-1/2 translate-x-1/2-translate-y-1/2">
          <div className="absolute top-[67px] bg-gray-100  h-[100px] w-[100px] "></div>
          <div className="absolute top-[67px] bg-blue-800  rounded-tl-[20px]  h-[100px] w-[100px] "></div>

          <div className="absolute top-[-167px] bg-gray-100 h-[100px] w-[100px] "></div>
          <div className="absolute top-[-167px] bg-blue-800  rounded-bl-[20px]   h-[100px] w-[100px] "></div>
        </div>
      </div>

   
    </div>
        </div>
      </body>
    </html>
  );
}

// import './globals.css';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
